/* ===================================================
   LINGKOD Meneses - Emoji library for the Messages composer.
   Hand-curated (no external CDN dependency) rather than a
   generated multi-thousand-entry dataset - every entry here is
   a real, renderable Unicode emoji with search keywords. The
   "Recently Used" and "Frequently Used" categories aren't in
   this file - they're built at runtime in messages/script.js
   from the per-account emoji_usage table (see the messaging
   attachments/emoji migration).
   =================================================== */

const LINGKOD_EMOJI_CATEGORIES = [
{ key:"smileys", label:"Smileys & Emotion", icon:"😀", emojis:[
["😀","grinning face"],["😃","grinning face big eyes"],["😄","grinning face smiling eyes"],["😁","beaming face smiling eyes"],
["😆","grinning squinting face laugh"],["😅","grinning face sweat laugh"],["🤣","rolling on the floor laughing laugh rofl"],["😂","face with tears of joy laugh lol"],
["🙂","slightly smiling face"],["🙃","upside down face"],["😉","winking face wink"],["😊","smiling face smiling eyes blush"],
["😇","smiling face with halo angel"],["🥰","smiling face with hearts love"],["😍","smiling face heart eyes love"],["🤩","star struck"],
["😘","face blowing a kiss love kiss"],["😗","kissing face"],["☺️","smiling face"],["😚","kissing face closed eyes"],
["😙","kissing face smiling eyes"],["🥲","smiling face with tear"],["😋","face savoring food yum"],["😛","face with tongue"],
["😜","winking face with tongue"],["🤪","zany face"],["😝","squinting face with tongue"],["🤑","money mouth face"],
["🤗","hugging face hug"],["🤭","face with hand over mouth"],["🫢","face with open eyes and hand over mouth"],["🫣","face with peeking eye"],
["🤫","shushing face quiet"],["🤔","thinking face think"],["🫡","saluting face"],["🤐","zipper mouth face"],
["🤨","face with raised eyebrow"],["😐","neutral face"],["😑","expressionless face"],["😶","face without mouth"],
["🫥","dotted line face"],["😏","smirking face smirk"],["😒","unamused face"],["🙄","face with rolling eyes eyeroll"],
["😬","grimacing face"],["🤥","lying face"],["😌","relieved face"],["😔","pensive face"],
["😪","sleepy face"],["🤤","drooling face"],["😴","sleeping face sleep"],["😷","face with medical mask sick"],
["🤒","face with thermometer sick"],["🤕","face with head bandage hurt"],["🤢","nauseated face sick"],["🤮","face vomiting sick"],
["🤧","sneezing face sick"],["🥵","hot face"],["🥶","cold face"],["🥴","woozy face"],
["😵","dizzy face"],["🤯","exploding head mind blown"],["🤠","cowboy hat face"],["🥳","partying face celebrate party"],
["🥸","disguised face"],["😎","smiling face with sunglasses cool"],["🤓","nerd face"],["🧐","face with monocle"],
["😕","confused face"],["🫤","face with diagonal mouth"],["😟","worried face"],["🙁","slightly frowning face"],
["☹️","frowning face"],["😮","face with open mouth wow surprised"],["😯","hushed face"],["😲","astonished face shocked"],
["😳","flushed face"],["🥺","pleading face"],["🥹","face holding back tears"],["😦","frowning face open mouth"],
["😧","anguished face"],["😨","fearful face scared"],["😰","anxious face with sweat"],["😥","sad but relieved face"],
["😢","crying face cry sad"],["😭","loudly crying face cry sad"],["😱","face screaming in fear scream"],["😖","confounded face"],
["😣","persevering face"],["😞","disappointed face sad"],["😓","downcast face with sweat"],["😩","weary face"],
["😫","tired face"],["🥱","yawning face tired"],["😤","face with steam from nose angry"],["😡","pouting face angry mad"],
["😠","angry face mad"],["🤬","face with symbols on mouth swearing angry"],["😈","smiling face with horns devil"],["👿","angry face with horns devil"],
["💀","skull death"],["☠️","skull and crossbones death"],["💩","pile of poo poop"],["🤡","clown face"],
["👹","ogre"],["👺","goblin"],["👻","ghost"],["👽","alien"],
["👾","alien monster"],["🤖","robot"],["😺","grinning cat"],["😸","grinning cat smiling eyes"],
["😹","cat with tears of joy laugh"],["😻","smiling cat heart eyes love"],["😼","cat with wry smile"],["😽","kissing cat"],
["🙀","weary cat scream"],["😿","crying cat sad"],["😾","pouting cat angry"]
]},
{ key:"people", label:"People & Body", icon:"🧑", emojis:[
["👋","waving hand wave hello"],["👋🏻","waving hand light skin tone"],["👋🏼","waving hand medium light skin tone"],["👋🏽","waving hand medium skin tone"],
["👋🏾","waving hand medium dark skin tone"],["👋🏿","waving hand dark skin tone"],["🤚","raised back of hand"],["🖐️","hand with fingers splayed"],
["✋","raised hand stop"],["🖖","vulcan salute"],["🫱","rightwards hand"],["🫲","leftwards hand"],
["🫳","palm down hand"],["🫴","palm up hand"],["👌","ok hand ok"],["🤌","pinched fingers"],
["🤏","pinching hand"],["✌️","victory hand peace"],["🤞","crossed fingers luck"],["🫰","hand with index finger and thumb crossed"],
["🤟","love you gesture"],["🤘","sign of the horns rock"],["🤙","call me hand"],["👈","backhand index pointing left"],
["👉","backhand index pointing right"],["👆","backhand index pointing up"],["🖕","middle finger"],["👇","backhand index pointing down"],
["☝️","index pointing up"],["🫵","index pointing at the viewer"],["👍","thumbs up like"],["👍🏻","thumbs up light skin tone"],
["👍🏼","thumbs up medium light skin tone"],["👍🏽","thumbs up medium skin tone"],["👍🏾","thumbs up medium dark skin tone"],["👍🏿","thumbs up dark skin tone"],
["👎","thumbs down dislike"],["✊","raised fist"],["👊","oncoming fist punch"],["🤛","left facing fist"],
["🤜","right facing fist"],["👏","clapping hands clap"],["👏🏻","clapping hands light skin tone"],["🙌","raising hands celebrate praise"],
["🙌🏻","raising hands light skin tone"],["👐","open hands"],["🤲","palms up together"],["🤝","handshake deal"],
["🙏","folded hands pray please thanks"],["🙏🏻","folded hands light skin tone"],["✍️","writing hand"],["💅","nail polish"],
["🤳","selfie"],["💪","flexed biceps strong muscle"],["💪🏻","flexed biceps light skin tone"],["🦾","mechanical arm"],
["🦵","leg"],["🦿","mechanical leg"],["🦶","foot"],["👂","ear"],
["🦻","ear with hearing aid"],["👃","nose"],["🧠","brain"],["🫀","anatomical heart"],
["🫁","lungs"],["🦷","tooth"],["🦴","bone"],["👀","eyes"],
["👁️","eye"],["👅","tongue"],["👄","mouth"],["🫦","biting lip"],
["👶","baby"],["🧒","child"],["👦","boy"],["👧","girl"],
["🧑","person"],["👱","person blond hair"],["👨","man"],["🧔","person beard"],
["👩","woman"],["🧓","older person"],["👴","old man"],["👵","old woman"],
["🙍","person frowning"],["🙎","person pouting"],["🙅","person gesturing no"],["🙆","person gesturing ok"],
["💁","person tipping hand"],["🙋","person raising hand"],["🧏","deaf person"],["🙇","person bowing"],
["🤦","person facepalming facepalm"],["🤷","person shrugging shrug"],["🧑‍⚕️","health worker doctor"],["🧑‍🎓","student graduate"],
["🧑‍🏫","teacher"],["🧑‍💼","office worker"],["🧑‍🔬","scientist"],["🧑‍💻","technologist programmer"],
["🧑‍🎤","singer"],["🧑‍🎨","artist"],["🧑‍✈️","pilot"],["🧑‍🚀","astronaut"],
["🧑‍🚒","firefighter"],["👮","police officer"],["🕵️","detective"],["💂","guard"],
["🥷","ninja"],["👷","construction worker"],["🤴","prince"],["👸","princess"],
["👳","person wearing turban"],["👲","person with skullcap"],["🧕","woman with headscarf"],["🤵","person in tuxedo"],
["👰","person with veil bride"],["🤰","pregnant woman"],["🤱","breast feeding"],["👼","baby angel"],
["🎅","santa claus"],["🤶","mrs claus"],["🦸","superhero"],["🦹","supervillain"],
["🧙","mage wizard"],["🧚","fairy"],["🧛","vampire"],["🧜","mermaid"],
["🧝","elf"],["🧞","genie"],["🧟","zombie"],["💆","person getting massage"],
["💇","person getting haircut"],["🚶","person walking"],["🧍","person standing"],["🧎","person kneeling"],
["🏃","person running run"],["💃","woman dancing dance"],["🕺","man dancing dance"],["🕴️","person in suit levitating"],
["👯","people with bunny ears"],["🧖","person in steamy room"],["🧗","person climbing"],["🤺","person fencing"],
["🏇","horse racing"],["⛷️","skier"],["🏂","snowboarder"],["🏌️","person golfing"],
["🏄","person surfing"],["🚣","person rowing boat"],["🏊","person swimming"],["⛹️","person bouncing ball"],
["🏋️","person lifting weights"],["🚴","person biking"],["🚵","person mountain biking"],["🤸","person cartwheeling"],
["🤼","people wrestling"],["🤽","person playing water polo"],["🤾","person playing handball"],["🤹","person juggling"],
["🧘","person in lotus position meditate"],["🛀","person taking bath"],["🛌","person in bed"],["👭","women holding hands"],
["👫","woman and man holding hands couple"],["👬","men holding hands"],["💏","kiss couple"],["💑","couple with heart love"],
["👪","family"],["🗣️","speaking head"],["👤","bust in silhouette"],["👥","busts in silhouette"],
["🫂","people hugging hug"]
]},
{ key:"animals", label:"Animals & Nature", icon:"🐶", emojis:[
["🐶","dog"],["🐱","cat"],["🐭","mouse"],["🐹","hamster"],
["🐰","rabbit"],["🦊","fox"],["🐻","bear"],["🐼","panda"],
["🐻‍❄️","polar bear"],["🐨","koala"],["🐯","tiger"],["🦁","lion"],
["🐮","cow"],["🐷","pig"],["🐽","pig nose"],["🐸","frog"],
["🐵","monkey"],["🙈","see no evil monkey"],["🙉","hear no evil monkey"],["🙊","speak no evil monkey"],
["🐔","chicken"],["🐧","penguin"],["🐦","bird"],["🐤","baby chick"],
["🐣","hatching chick"],["🐥","front facing baby chick"],["🦆","duck"],["🦅","eagle"],
["🦉","owl"],["🦇","bat"],["🐺","wolf"],["🐗","boar"],
["🐴","horse"],["🦄","unicorn"],["🐝","bee"],["🪱","worm"],
["🐛","bug"],["🦋","butterfly"],["🐌","snail"],["🐞","lady beetle"],
["🐜","ant"],["🪰","fly"],["🪲","beetle"],["🪳","cockroach"],
["🦟","mosquito"],["🦗","cricket"],["🕷️","spider"],["🕸️","spider web"],
["🦂","scorpion"],["🐢","turtle"],["🐍","snake"],["🦎","lizard"],
["🦖","t rex dinosaur"],["🦕","sauropod dinosaur"],["🐙","octopus"],["🦑","squid"],
["🦐","shrimp"],["🦞","lobster"],["🦀","crab"],["🐡","blowfish"],
["🐠","tropical fish"],["🐟","fish"],["🐬","dolphin"],["🐳","whale"],
["🐋","whale"],["🦈","shark"],["🐊","crocodile"],["🐅","tiger"],
["🐆","leopard"],["🦓","zebra"],["🦍","gorilla"],["🦧","orangutan"],
["🐘","elephant"],["🦣","mammoth"],["🦛","hippopotamus"],["🦏","rhinoceros"],
["🐪","camel"],["🐫","two hump camel"],["🦒","giraffe"],["🦘","kangaroo"],
["🦬","bison"],["🐃","water buffalo"],["🐂","ox"],["🐄","cow"],
["🐎","horse"],["🐖","pig"],["🐏","ram"],["🐑","sheep"],
["🦙","llama"],["🐐","goat"],["🦌","deer"],["🐕","dog"],
["🐩","poodle"],["🦮","guide dog"],["🐕‍🦺","service dog"],["🐈","cat"],
["🐈‍⬛","black cat"],["🪶","feather"],["🐓","rooster"],["🦃","turkey"],
["🦤","dodo"],["🦚","peacock"],["🦜","parrot"],["🦢","swan"],
["🦩","flamingo"],["🕊️","dove peace"],["🐇","rabbit"],["🦝","raccoon"],
["🦨","skunk"],["🦡","badger"],["🦫","beaver"],["🦦","otter"],
["🦥","sloth"],["🐁","mouse"],["🐀","rat"],["🐿️","chipmunk"],
["🦔","hedgehog"],["🐾","paw prints"],["🐉","dragon"],["🐲","dragon face"],
["🌵","cactus"],["🎄","christmas tree"],["🌲","evergreen tree"],["🌳","deciduous tree"],
["🌴","palm tree"],["🪴","potted plant"],["🌱","seedling"],["🌿","herb"],
["☘️","shamrock"],["🍀","four leaf clover luck"],["🎍","pine decoration"],["🎋","tanabata tree"],
["🍃","leaves"],["🍂","fallen leaf"],["🍁","maple leaf"],["🍄","mushroom"],
["🐚","shell"],["🪨","rock"],["🌾","sheaf of rice"],["💐","bouquet"],
["🌷","tulip"],["🌹","rose"],["🥀","wilted flower"],["🪷","lotus"],
["🌺","hibiscus"],["🌸","cherry blossom"],["🌼","blossom"],["🌻","sunflower"],
["🌞","sun with face"],["🌝","full moon with face"],["🌛","first quarter moon with face"],["🌜","last quarter moon with face"],
["🌚","new moon with face"],["🌕","full moon"],["🌖","waning gibbous moon"],["🌗","last quarter moon"],
["🌘","waning crescent moon"],["🌑","new moon"],["🌒","waxing crescent moon"],["🌓","first quarter moon"],
["🌔","waxing gibbous moon"],["🌙","crescent moon"],["🌎","earth globe americas"],["🌍","earth globe europe africa"],
["🌏","earth globe asia australia"],["🪐","ringed planet"],["💫","dizzy stars"],["⭐","star"],
["🌟","glowing star"],["✨","sparkles"],["⚡","lightning bolt"],["☄️","comet"],
["💥","collision boom"],["🔥","fire"],["🌪️","tornado"],["🌈","rainbow"],
["☀️","sun"],["🌤️","sun behind small cloud"],["⛅","sun behind cloud"],["🌥️","sun behind large cloud"],
["☁️","cloud"],["🌦️","sun behind rain cloud"],["🌧️","cloud with rain"],["⛈️","cloud with lightning and rain"],
["🌩️","cloud with lightning"],["❄️","snowflake"],["☃️","snowman"],["⛄","snowman without snow"],
["🌬️","wind face"],["💨","dashing away wind"],["💧","droplet"],["💦","sweat droplets"],
["☔","umbrella with rain drops"],["🌊","water wave"]
]},
{ key:"food", label:"Food & Drink", icon:"🍔", emojis:[
["🍏","green apple"],["🍎","red apple"],["🍐","pear"],["🍊","tangerine orange"],
["🍋","lemon"],["🍌","banana"],["🍉","watermelon"],["🍇","grapes"],
["🍓","strawberry"],["🫐","blueberries"],["🍈","melon"],["🍒","cherries"],
["🍑","peach"],["🥭","mango"],["🍍","pineapple"],["🥥","coconut"],
["🥝","kiwi fruit"],["🍅","tomato"],["🍆","eggplant"],["🥑","avocado"],
["🥦","broccoli"],["🥬","leafy green"],["🥒","cucumber"],["🌶️","hot pepper"],
["🫑","bell pepper"],["🌽","corn"],["🥕","carrot"],["🫒","olive"],
["🧄","garlic"],["🧅","onion"],["🥔","potato"],["🍠","roasted sweet potato"],
["🥐","croissant"],["🥯","bagel"],["🍞","bread"],["🥖","baguette bread"],
["🥨","pretzel"],["🧀","cheese wedge"],["🥚","egg"],["🍳","cooking fried egg"],
["🧈","butter"],["🥞","pancakes"],["🧇","waffle"],["🥓","bacon"],
["🥩","cut of meat"],["🍗","poultry leg chicken"],["🍖","meat on bone"],["🌭","hot dog"],
["🍔","hamburger burger"],["🍟","french fries fries"],["🍕","pizza"],["🫓","flatbread"],
["🥪","sandwich"],["🥙","stuffed flatbread"],["🧆","falafel"],["🌮","taco"],
["🌯","burrito"],["🫔","tamale"],["🥗","green salad salad"],["🥘","shallow pan of food"],
["🫕","fondue"],["🥫","canned food"],["🍝","spaghetti pasta"],["🍜","steaming bowl ramen noodles"],
["🍲","pot of food stew"],["🍛","curry rice"],["🍣","sushi"],["🍱","bento box"],
["🥟","dumpling"],["🦪","oyster"],["🍤","fried shrimp tempura"],["🍙","rice ball"],
["🍚","cooked rice"],["🍘","rice cracker"],["🍥","fish cake with swirl"],["🥠","fortune cookie"],
["🥮","moon cake"],["🍢","oden"],["🍡","dango"],["🍧","shaved ice"],
["🍨","ice cream"],["🍦","soft ice cream"],["🥧","pie"],["🧁","cupcake"],
["🍰","shortcake cake"],["🎂","birthday cake cake"],["🍮","custard"],["🍭","lollipop candy"],
["🍬","candy"],["🍫","chocolate bar"],["🍿","popcorn"],["🍩","doughnut donut"],
["🍪","cookie"],["🌰","chestnut"],["🥜","peanuts"],["🍯","honey pot"],
["🥛","glass of milk"],["🍼","baby bottle"],["☕","hot beverage coffee"],["🍵","teacup without handle tea"],
["🧃","beverage box juice"],["🥤","cup with straw soda"],["🧋","bubble tea"],["🍶","sake"],
["🍺","beer mug"],["🍻","clinking beer mugs cheers"],["🥂","clinking glasses cheers"],["🍷","wine glass wine"],
["🥃","tumbler glass whiskey"],["🍸","cocktail glass"],["🍹","tropical drink"],["🧉","mate"],
["🍾","bottle with popping cork champagne"],["🧊","ice"],["🥄","spoon"],["🍴","fork and knife"],
["🍽️","fork and knife with plate"],["🥢","chopsticks"],["🧂","salt"]
]},
{ key:"activities", label:"Activities & Sports", icon:"⚽", emojis:[
["⚽","soccer ball football"],["🏀","basketball"],["🏈","american football"],["⚾","baseball"],
["🥎","softball"],["🎾","tennis"],["🏐","volleyball"],["🏉","rugby football"],
["🎱","pool 8 ball billiards"],["🪀","yo yo"],["🏓","ping pong table tennis"],["🏸","badminton"],
["🏒","ice hockey"],["🏑","field hockey"],["🥍","lacrosse"],["🏏","cricket game"],
["🪃","boomerang"],["🥅","goal net"],["⛳","flag in hole golf"],["🪁","kite"],
["🏹","bow and arrow archery"],["🎣","fishing pole"],["🤿","diving mask"],["🥊","boxing glove"],
["🥋","martial arts uniform"],["🎽","running shirt"],["🛹","skateboard"],["🛼","roller skate"],
["🛷","sled"],["⛸️","ice skate"],["🥌","curling stone"],["🎿","skis"],
["🪂","parachute"],["🏆","trophy win"],["🥇","first place medal gold"],["🥈","second place medal silver"],
["🥉","third place medal bronze"],["🏅","sports medal"],["🎖️","military medal"],["🏵️","rosette"],
["🎗️","reminder ribbon"],["🎫","ticket"],["🎟️","admission tickets"],["🎪","circus tent"],
["🤹","juggling"],["🎭","performing arts theater"],["🩰","ballet shoes"],["🎨","artist palette art"],
["🎬","clapper board movie"],["🎤","microphone sing"],["🎧","headphone music"],["🎼","musical score"],
["🎹","musical keyboard piano"],["🥁","drum"],["🪘","long drum"],["🎷","saxophone"],
["🎺","trumpet"],["🎸","guitar"],["🪕","banjo"],["🎻","violin"],
["🎲","game die dice"],["♟️","chess pawn"],["🎯","direct hit dart target"],["🎳","bowling"],
["🎮","video game controller"],["🎰","slot machine"]
]},
{ key:"celebration", label:"Celebration", icon:"🎉", emojis:[
["🎉","party popper celebrate"],["🎊","confetti ball celebrate"],["🎈","balloon party"],["🎆","fireworks"],
["🎇","sparkler"],["🧨","firecracker"],["🎀","ribbon"],["🎁","wrapped gift present"],
["🥳","partying face"],["🪅","pinata"],["🪄","magic wand"],["🎑","moon viewing ceremony"],
["🎐","wind chime"],["🧧","red envelope"],["🎏","carp streamer"],["🎂","birthday cake"]
]},
{ key:"travel", label:"Travel & Places", icon:"🚗", emojis:[
["🚗","car automobile"],["🚕","taxi"],["🚙","sport utility vehicle suv"],["🚌","bus"],
["🚎","trolleybus"],["🏎️","racing car"],["🚓","police car"],["🚑","ambulance"],
["🚒","fire engine"],["🚐","minibus"],["🛻","pickup truck"],["🚚","delivery truck"],
["🚛","articulated lorry truck"],["🚜","tractor"],["🦯","white cane"],["🦽","manual wheelchair"],
["🦼","motorized wheelchair"],["🩼","crutch"],["🛴","kick scooter"],["🚲","bicycle bike"],
["🛵","motor scooter"],["🏍️","motorcycle"],["🛺","auto rickshaw"],["🚨","police car light siren"],
["🚔","oncoming police car"],["🚍","oncoming bus"],["🚘","oncoming automobile"],["🚖","oncoming taxi"],
["🚡","aerial tramway"],["🚠","mountain cableway"],["🚟","suspension railway"],["🚃","railway car"],
["🚋","tram car"],["🚞","mountain railway"],["🚝","monorail"],["🚄","high speed train"],
["🚅","bullet train"],["🚈","light rail"],["🚂","locomotive train"],["🚆","train"],
["🚇","metro subway"],["🚊","tram"],["🚉","station"],["✈️","airplane flight"],
["🛫","airplane departure"],["🛬","airplane arrival"],["🛩️","small airplane"],["💺","seat"],
["🛰️","satellite"],["🚀","rocket space"],["🛸","flying saucer ufo"],["🚁","helicopter"],
["🛶","canoe"],["⛵","sailboat"],["🚤","speedboat"],["🛥️","motor boat"],
["🛳️","passenger ship"],["⛴️","ferry"],["🚢","ship"],["⚓","anchor"],
["🪝","hook"],["⛽","fuel pump gas"],["🚧","construction sign"],["🚦","traffic light"],
["🚥","horizontal traffic light"],["🗺️","world map"],["🗿","moai statue"],["🗽","statue of liberty"],
["🗼","tokyo tower"],["🏰","castle"],["🏯","japanese castle"],["🏟️","stadium"],
["🎡","ferris wheel"],["🎢","roller coaster"],["🎠","carousel horse"],["⛲","fountain"],
["⛱️","umbrella on ground"],["🏖️","beach with umbrella"],["🏝️","desert island"],["🏜️","desert"],
["🌋","volcano"],["⛰️","mountain"],["🏔️","snow capped mountain"],["🗻","mount fuji"],
["🏕️","camping"],["⛺","tent"],["🏠","house"],["🏡","house with garden"],
["🏘️","houses"],["🏚️","derelict house"],["🏗️","building construction"],["🏭","factory"],
["🏢","office building"],["🏬","department store"],["🏣","japanese post office"],["🏤","post office"],
["🏥","hospital"],["🏦","bank"],["🏨","hotel"],["🏪","convenience store"],
["🏫","school"],["🏩","love hotel"],["💒","wedding"],["🏛️","classical building"],
["⛪","church"],["🕌","mosque"],["🕍","synagogue"],["🛕","hindu temple"],
["🕋","kaaba"],["⛩️","shinto shrine"],["🌁","foggy bridge"],["🌃","night with stars"],
["🏙️","cityscape"],["🌄","sunrise over mountains"],["🌅","sunrise"],["🌆","cityscape at dusk"],
["🌇","sunset"],["🌉","bridge at night"],["♨️","hot springs"],["🌌","milky way"]
]},
{ key:"objects", label:"Objects", icon:"💡", emojis:[
["⌚","watch"],["📱","mobile phone"],["💻","laptop computer"],["⌨️","keyboard"],
["🖥️","desktop computer"],["🖨️","printer"],["🖱️","computer mouse"],["🖲️","trackball"],
["🕹️","joystick"],["🗜️","clamp"],["💽","computer disk"],["💾","floppy disk save"],
["💿","optical disk cd"],["📀","dvd"],["📼","videocassette"],["📷","camera"],
["📸","camera with flash"],["📹","video camera"],["🎥","movie camera"],["📽️","film projector"],
["🎞️","film frames"],["📞","telephone receiver call"],["☎️","telephone"],["📟","pager"],
["📠","fax machine"],["📺","television tv"],["📻","radio"],["🎙️","studio microphone"],
["🎚️","level slider"],["🎛️","control knobs"],["🧭","compass"],["⏱️","stopwatch"],
["⏲️","timer clock"],["⏰","alarm clock"],["🕰️","mantelpiece clock"],["⌛","hourglass done"],
["⏳","hourglass not done time"],["📡","satellite antenna"],["🔋","battery"],["🪫","low battery"],
["🔌","electric plug"],["💡","light bulb idea"],["🔦","flashlight"],["🕯️","candle"],
["🪔","diya lamp"],["🧯","fire extinguisher"],["🛢️","oil drum"],["💸","money with wings"],
["💵","dollar banknote money"],["💴","yen banknote"],["💶","euro banknote"],["💷","pound banknote"],
["🪙","coin"],["💰","money bag"],["💳","credit card"],["🧾","receipt"],
["💎","gem stone diamond"],["⚖️","balance scale"],["🪜","ladder"],["🧰","toolbox"],
["🪛","screwdriver"],["🔧","wrench"],["🔨","hammer"],["⚒️","hammer and pick"],
["🛠️","hammer and wrench"],["⛏️","pick"],["🪚","carpentry saw"],["🔩","nut and bolt"],
["⚙️","gear settings"],["🪤","mouse trap"],["🧱","brick"],["⛓️","chains"],
["🧲","magnet"],["💣","bomb"],["🪓","axe"],["🔪","kitchen knife"],
["🗡️","dagger"],["⚔️","crossed swords"],["🛡️","shield"],["🚬","cigarette"],
["⚰️","coffin"],["🪦","headstone"],["⚱️","funeral urn"],["🏺","amphora"],
["🔮","crystal ball"],["📿","prayer beads"],["🧿","nazar amulet"],["💈","barber pole"],
["⚗️","alembic"],["🔭","telescope"],["🔬","microscope"],["🕳️","hole"],
["🩹","adhesive bandage"],["🩺","stethoscope"],["💊","pill medicine"],["💉","syringe"],
["🩸","drop of blood"],["🧬","dna"],["🦠","microbe"],["🧫","petri dish"],
["🧪","test tube"],["🌡️","thermometer"],["🧹","broom"],["🪠","plunger"],
["🧺","basket"],["🧻","roll of paper toilet paper"],["🚽","toilet"],["🚰","potable water"],
["🚿","shower"],["🛁","bathtub"],["🧼","soap"],["🪥","toothbrush"],
["🪒","razor"],["🧴","lotion bottle"],["🧷","safety pin"],["🧵","thread"],
["🪡","sewing needle"],["🧶","yarn"],["🪢","knot"],["🛍️","shopping bags"],
["🎒","backpack"],["🩴","thong sandal"],["👞","mans shoe"],["👟","running shoe sneaker"],
["🥾","hiking boot"],["👠","high heeled shoe"],["👡","woman sandal"],["👢","woman boot"],
["👑","crown"],["👒","woman hat"],["🎩","top hat"],["🎓","graduation cap"],
["🧢","billed cap"],["🪖","military helmet"],["⛑️","rescue worker helmet"],["💄","lipstick"],
["💍","ring"],["🌂","closed umbrella"],["🕶️","sunglasses"],["🥽","goggles"],
["🥼","lab coat"],["🦺","safety vest"],["👔","necktie"],["👕","t shirt"],
["👖","jeans"],["🧣","scarf"],["🧤","gloves"],["🧥","coat"],
["🧦","socks"],["👗","dress"],["👘","kimono"],["🥻","sari"],
["🩱","one piece swimsuit"],["🩲","briefs"],["🩳","shorts"],["👙","bikini"],
["👚","womans clothes"],["👛","purse"],["👜","handbag"],["💼","briefcase"],
["📔","notebook with decorative cover"],["📕","closed book"],["📖","open book"],["📗","green book"],
["📘","blue book"],["📙","orange book"],["📚","books"],["📓","notebook"],
["📒","ledger"],["📃","page with curl"],["📜","scroll"],["📄","page facing up"],
["📰","newspaper"],["🗞️","rolled up newspaper"],["📑","bookmark tabs"],["🔖","bookmark"],
["🏷️","label tag"],["✉️","envelope email"],["📧","e mail"],["📨","incoming envelope"],
["📩","envelope with arrow"],["📤","outbox tray"],["📥","inbox tray"],["📦","package box"],
["📫","closed mailbox with raised flag"],["📪","closed mailbox with lowered flag"],["📬","open mailbox with raised flag"],["📭","open mailbox with lowered flag"],
["📮","postbox"],["🗳️","ballot box"],["✏️","pencil"],["✒️","black nib"],
["🖋️","fountain pen"],["🖊️","pen"],["🖌️","paintbrush"],["🖍️","crayon"],
["📝","memo note"],["📁","file folder"],["📂","open file folder"],["🗂️","card index dividers"],
["📅","calendar"],["📆","tear off calendar"],["🗒️","spiral notepad"],["🗓️","spiral calendar"],
["📇","card index"],["📈","chart increasing"],["📉","chart decreasing"],["📊","bar chart"],
["📋","clipboard"],["📌","pushpin"],["📍","round pushpin location"],["📎","paperclip"],
["🖇️","linked paperclips"],["📏","straight ruler"],["📐","triangular ruler"],["✂️","scissors"],
["🗃️","card file box"],["🗄️","file cabinet"],["🗑️","wastebasket trash"],["🔒","locked lock"],
["🔓","unlocked"],["🔏","locked with pen"],["🔐","locked with key"],["🔑","key"],
["🗝️","old key"],["🔗","link chain"],["🔎","magnifying glass tilted"],["🔍","magnifying glass search"]
]},
{ key:"symbols", label:"Symbols", icon:"❤️", emojis:[
["❤️","red heart love"],["🧡","orange heart"],["💛","yellow heart"],["💚","green heart"],
["💙","blue heart"],["💜","purple heart"],["🖤","black heart"],["🤍","white heart"],
["🤎","brown heart"],["💔","broken heart"],["❣️","heart exclamation"],["💕","two hearts love"],
["💞","revolving hearts love"],["💓","beating heart love"],["💗","growing heart love"],["💖","sparkling heart love"],
["💘","heart with arrow love"],["💝","heart with ribbon love"],["💟","heart decoration"],["🩷","pink heart"],
["🩵","light blue heart"],["🩶","grey heart"],["♥️","heart suit"],["💯","hundred points"],
["💢","anger symbol"],["💥","collision"],["💫","dizzy"],["💦","sweat droplets"],
["💨","dash"],["💣","bomb"],["💬","speech balloon"],["🗨️","left speech bubble"],
["🗯️","right anger bubble"],["💭","thought balloon"],["💤","zzz sleep"],["✅","check mark"],
["☑️","check box"],["✔️","heavy check mark"],["❌","cross mark x"],["❎","cross mark button"],
["➕","plus"],["➖","minus"],["➗","divide"],["✖️","multiply"],
["♾️","infinity"],["‼️","double exclamation"],["⁉️","exclamation question"],["❓","question mark"],
["❔","white question mark"],["❕","white exclamation"],["❗","exclamation mark"],["🔥","fire"],
["⭐","star"],["🌟","glowing star"],["✨","sparkles"],["⚡","lightning"],
["🚫","no entry prohibited"],["⛔","no entry"],["📛","name badge"],["🔞","no one under eighteen"],
["📵","no mobile phones"],["🚭","no smoking"],["🔅","low brightness"],["🔆","high brightness"],
["🔱","trident"],["⚜️","fleur de lis"],["🔰","japanese symbol beginner"],["♻️","recycling symbol"],
["🈯","japanese reserved button"],["💹","chart increasing with yen"],["❇️","sparkle"],["✳️","eight spoked asterisk"],
["🌐","globe with meridians"],["💠","diamond with a dot"],["Ⓜ️","circled m"],["🌀","cyclone"],
["🏧","atm sign"],["🚾","water closet"],["♿","wheelchair symbol"],["🅿️","parking button"],
["🈳","japanese vacancy"],["🈂️","japanese service charge"],["🛂","passport control"],["🛃","customs"],
["🛄","baggage claim"],["🛅","left luggage"],["🚹","mens room"],["🚺","womens room"],
["🚼","baby symbol"],["🚻","restroom"],["🚮","litter in bin"],["🎦","cinema"],
["📶","antenna bars signal"],["🈁","japanese here"],["🔣","input symbols"],["ℹ️","information"],
["🔤","abcd input latin letters"],["🔡","abcd input latin lowercase"],["🔠","abcd input latin uppercase"],["🆖","ng button"],
["🆗","ok button"],["🆙","up button"],["🆒","cool button"],["🆕","new button"],
["🆓","free button"],["0️⃣","keycap 0"],["1️⃣","keycap 1"],["2️⃣","keycap 2"],
["3️⃣","keycap 3"],["4️⃣","keycap 4"],["5️⃣","keycap 5"],["6️⃣","keycap 6"],
["7️⃣","keycap 7"],["8️⃣","keycap 8"],["9️⃣","keycap 9"],["🔟","keycap 10"],
["🔢","input numbers"],["#️⃣","keycap hash"],["*️⃣","keycap asterisk"],["⏏️","eject button"],
["▶️","play button"],["⏸️","pause button"],["⏯️","play pause button"],["⏹️","stop button"],
["⏺️","record button"],["⏭️","next track button"],["⏮️","last track button"],["⏩","fast forward button"],
["⏪","fast reverse button"],["⏫","fast up button"],["⏬","fast down button"],["◀️","reverse button"],
["🔼","upwards button"],["🔽","downwards button"],["➡️","right arrow"],["⬅️","left arrow"],
["⬆️","up arrow"],["⬇️","down arrow"],["↗️","up right arrow"],["↘️","down right arrow"],
["↙️","down left arrow"],["↖️","up left arrow"],["↕️","up down arrow"],["↔️","left right arrow"],
["↩️","right arrow curving left"],["↪️","left arrow curving right"],["🔀","shuffle tracks button"],["🔁","repeat button"],
["🔂","repeat single button"],["🔄","counterclockwise arrows button refresh"],["🔃","clockwise vertical arrows"],["🎵","musical note"],
["🎶","musical notes"],["➰","curly loop"],["➿","double curly loop"],["🔚","end arrow"],
["🔙","back arrow"],["🔛","on arrow"],["🔝","top arrow"],["🛐","place of worship"],
["⚛️","atom symbol"],["🕉️","om"],["✡️","star of david"],["☸️","wheel of dharma"],
["☯️","yin yang"],["✝️","latin cross"],["☦️","orthodox cross"],["☪️","star and crescent"],
["☮️","peace symbol"],["🕎","menorah"],["🔯","dotted six pointed star"],["♈","aries"],
["♉","taurus"],["♊","gemini"],["♋","cancer"],["♌","leo"],
["♍","virgo"],["♎","libra"],["♏","scorpio"],["♐","sagittarius"],
["♑","capricorn"],["♒","aquarius"],["♓","pisces"],["⛎","ophiuchus"],
["🔴","red circle"],["🟠","orange circle"],["🟡","yellow circle"],["🟢","green circle"],
["🔵","blue circle"],["🟣","purple circle"],["🟤","brown circle"],["⚫","black circle"],
["⚪","white circle"],["🟥","red square"],["🟧","orange square"],["🟨","yellow square"],
["🟩","green square"],["🟦","blue square"],["🟪","purple square"],["🟫","brown square"],
["⬛","black large square"],["⬜","white large square"],["◼️","black medium square"],["◻️","white medium square"],
["🔶","large orange diamond"],["🔷","large blue diamond"],["🔸","small orange diamond"],["🔹","small blue diamond"],
["🔺","red triangle pointed up"],["🔻","red triangle pointed down"],["🔘","radio button"],["🔳","white square button"],
["🔲","black square button"]
]},
{ key:"flags", label:"Flags", icon:"🚩", emojis:[
["🏳️","white flag"],["🏴","black flag"],["🏁","checkered flag"],["🚩","triangular flag"],
["🏳️‍🌈","rainbow flag pride"],["🏳️‍⚧️","transgender flag"],["🏴‍☠️","pirate flag"],["🇵🇭","philippines flag"],
["🇺🇸","united states flag"],["🇬🇧","united kingdom flag"],["🇨🇦","canada flag"],["🇦🇺","australia flag"],
["🇯🇵","japan flag"],["🇰🇷","south korea flag"],["🇨🇳","china flag"],["🇮🇳","india flag"],
["🇩🇪","germany flag"],["🇫🇷","france flag"],["🇮🇹","italy flag"],["🇪🇸","spain flag"],
["🇧🇷","brazil flag"],["🇲🇽","mexico flag"],["🇷🇺","russia flag"],["🇸🇬","singapore flag"],
["🇲🇾","malaysia flag"],["🇮🇩","indonesia flag"],["🇹🇭","thailand flag"],["🇻🇳","vietnam flag"],
["🇸🇦","saudi arabia flag"],["🇦🇪","united arab emirates flag"],["🇿🇦","south africa flag"],["🇳🇿","new zealand flag"],
["🇳🇱","netherlands flag"],["🇸🇪","sweden flag"],["🇨🇭","switzerland flag"],["🇵🇹","portugal flag"],
["🇬🇷","greece flag"],["🇹🇷","turkey flag"],["🇪🇬","egypt flag"],["🇦🇷","argentina flag"],
["🇺🇳","united nations flag"]
]}
];
